const CountryData = [
  { value: "AF", flag: "AFG", text: "Afghanistan" },
  { value: "AL", flag: "ALB", text: "Albania" },
  { value: "DZ", flag: "DZA", text: "Algeria" },
  { value: "AS", flag: "ASM", text: "American Samoa" },
  { value: "AD", flag: "AND", text: "Andorra" },
  { value: "AO", flag: "AGO", text: "Angola" },
  { value: "AI", flag: "AIA", text: "Anguilla" },
  { value: "AQ", flag: "ATA", text: "Antarctica" },
  { value: "AG", flag: "ATG", text: "Antigua and Barbuda" },
  { value: "AR", flag: "ARG", text: "Argentina" },
  { value: "AM", flag: "ARM", text: "Armenia" },
  { value: "AW", flag: "ABW", text: "Aruba" },
  { value: "AU", flag: "AUS", text: "Australia" },
  { value: "AT", flag: "AUT", text: "Austria" },
  { value: "AZ", flag: "AZE", text: "Azerbaijan" },
  { value: "BS", flag: "BHS", text: "Bahamas (the)" },
  { value: "BH", flag: "BHR", text: "Bahrain" },
  { value: "BD", flag: "BGD", text: "Bangladesh" },
  { value: "BB", flag: "BRB", text: "Barbados" },
  { value: "BY", flag: "BLR", text: "Belarus" },
  { value: "BE", flag: "BEL", text: "Belgium" },
  { value: "BZ", flag: "BLZ", text: "Belize" },
  { value: "BJ", flag: "BEN", text: "Benin" },
  { value: "BM", flag: "BMU", text: "Bermuda" },
  { value: "BT", flag: "BTN", text: "Bhutan" },
  { value: "BO", flag: "BOL", text: "Bolivia (Plurinational State of)" },
  { value: "BQ", flag: "BES", text: "Bonaire, Sint Eustatius and Saba" },
  { value: "BA", flag: "BIH", text: "Bosnia and Herzegovina" },
  { value: "BW", flag: "BWA", text: "Botswana" },
  { value: "BV", flag: "BVT", text: "Bouvet Island" },
  { value: "BR", flag: "BRA", text: "Brazil" },
  { value: "IO", flag: "IOT", text: "British Indian Ocean Territory (the)" },
  { value: "BN", flag: "BRN", text: "Brunei Darussalam" },
  { value: "BG", flag: "BGR", text: "Bulgaria" },
  { value: "BF", flag: "BFA", text: "Burkina Faso" },
  { value: "BI", flag: "BDI", text: "Burundi" },
  { value: "CV", flag: "CPV", text: "Cabo Verde" },
  { value: "KH", flag: "KHM", text: "Cambodia" },
  { value: "CM", flag: "CMR", text: "Cameroon" },
  { value: "CA", flag: "CAN", text: "Canada" },
  { value: "KY", flag: "CYM", text: "Cayman Islands (the)" },
  { value: "CF", flag: "CAF", text: "Central African Republic (the)" },
  { value: "TD", flag: "TCD", text: "Chad" },
  { value: "CL", flag: "CHL", text: "Chile" },
  { value: "CN", flag: "CHN", text: "China" },
  { value: "CX", flag: "CXR", text: "Christmas Island" },
  { value: "CC", flag: "CCK", text: "Cocos (Keeling) Islands (the)" },
  { value: "CO", flag: "COL", text: "Colombia" },
  { value: "KM", flag: "COM", text: "Comoros (the)" },
  {
    value: "CD",
    flag: "COD",
    text: "Congo (the Democratic Republic of the)",
  },
  { value: "CG", flag: "COG", text: "Congo (the)" },
  { value: "CK", flag: "COK", text: "Cook Islands (the)" },
  { value: "CR", flag: "CRI", text: "Costa Rica" },
  { value: "HR", flag: "HRV", text: "Croatia" },
  { value: "CU", flag: "CUB", text: "Cuba" },
  { value: "CW", flag: "CUW", text: "Curaçao" },
  { value: "CY", flag: "CYP", text: "Cyprus" },
  { value: "CZ", flag: "CZE", text: "Czechia" },
  { value: "CI", flag: "CIV", text: "Côte d'Ivoire" },
  { value: "DK", flag: "DNK", text: "Denmark" },
  { value: "DJ", flag: "DJI", text: "Djibouti" },
  { value: "DM", flag: "DMA", text: "Dominica" },
  { value: "DO", flag: "DOM", text: "Dominican Republic (the)" },
  { value: "EC", flag: "ECU", text: "Ecuador" },
  { value: "EG", flag: "EGY", text: "Egypt" },
  { value: "SV", flag: "SLV", text: "El Salvador" },
  { value: "GQ", flag: "GNQ", text: "Equatorial Guinea" },
  { value: "ER", flag: "ERI", text: "Eritrea" },
  { value: "EE", flag: "EST", text: "Estonia" },
  { value: "SZ", flag: "SWZ", text: "Eswatini" },
  { value: "ET", flag: "ETH", text: "Ethiopia" },
  { value: "FK", flag: "FLK", text: "Falkland Islands (the) [Malvinas]" },
  { value: "FO", flag: "FRO", text: "Faroe Islands (the)" },
  { value: "FJ", flag: "FJI", text: "Fiji" },
  { value: "FI", flag: "FIN", text: "Finland" },
  { value: "FR", flag: "FRA", text: "France" },
  { value: "GF", flag: "GUF", text: "French Guiana" },
  { value: "PF", flag: "PYF", text: "French Polynesia" },
  { value: "TF", flag: "ATF", text: "French Southern Territories (the)" },
  { value: "GA", flag: "GAB", text: "Gabon" },
  { value: "GM", flag: "GMB", text: "Gambia (the)" },
  { value: "GE", flag: "GEO", text: "Georgia" },
  { value: "DE", flag: "DEU", text: "Germany" },
  { value: "GH", flag: "GHA", text: "Ghana" },
  { value: "GI", flag: "GIB", text: "Gibraltar" },
  { value: "GR", flag: "GRC", text: "Greece" },
  { value: "GL", flag: "GRL", text: "Greenland" },
  { value: "GD", flag: "GRD", text: "Grenada" },
  { value: "GP", flag: "GLP", text: "Guadeloupe" },
  { value: "GU", flag: "GUM", text: "Guam" },
  { value: "GT", flag: "GTM", text: "Guatemala" },
  { value: "GG", flag: "GGY", text: "Guernsey" },
  { value: "GN", flag: "GIN", text: "Guinea" },
  { value: "GW", flag: "GNB", text: "Guinea-Bissau" },
  { value: "GY", flag: "GUY", text: "Guyana" },
  { value: "HT", flag: "HTI", text: "Haiti" },
  { value: "HM", flag: "HMD", text: "Heard Island and McDonald Islands" },
  { value: "VA", flag: "VAT", text: "Holy See (the)" },
  { value: "HN", flag: "HND", text: "Honduras" },
  { value: "HK", flag: "HKG", text: "Hong Kong" },
  { value: "HU", flag: "HUN", text: "Hungary" },
  { value: "IS", flag: "ISL", text: "Iceland" },
  { value: "IN", flag: "IND", text: "India" },
  { value: "ID", flag: "IDN", text: "Indonesia" },
  { value: "IR", flag: "IRN", text: "Iran (Islamic Republic of)" },
  { value: "IQ", flag: "IRQ", text: "Iraq" },
  { value: "IE", flag: "IRL", text: "Ireland" },
  { value: "IM", flag: "IMN", text: "Isle of Man" },
  { value: "IL", flag: "ISR", text: "Israel" },
  { value: "IT", flag: "ITA", text: "Italy" },
  { value: "JM", flag: "JAM", text: "Jamaica" },
  { value: "JP", flag: "JPN", text: "Japan" },
  { value: "JE", flag: "JEY", text: "Jersey" },
  { value: "JO", flag: "JOR", text: "Jordan" },
  { value: "KZ", flag: "KAZ", text: "Kazakhstan" },
  { value: "KE", flag: "KEN", text: "Kenya" },
  { value: "KI", flag: "KIR", text: "Kiribati" },
  {
    value: "KP",
    flag: "PRK",
    text: "Korea (the Democratic People's Republic of)",
  },
  { value: "KR", flag: "KOR", text: "Korea (the Republic of0" },
  { value: "KW", flag: "KWT", text: "Kuwait" },
  { value: "KG", flag: "KGZ", text: "Kyrgyzstan" },
  {
    value: "LA",
    flag: "LAO",
    text: "Lao People's Democratic Republic (the)",
  },
  { value: "LV", flag: "LVA", text: "Latvia" },
  { value: "LB", flag: "LBN", text: "Lebanon" },
  { value: "LS", flag: "LSO", text: "Lesotho" },
  { value: "LR", flag: "LBR", text: "Liberia" },
  { value: "LY", flag: "LBY", text: "Libya" },
  { value: "LI", flag: "LIE", text: "Liechtenstein" },
  { value: "LT", flag: "LTU", text: "Lithuania" },
  { value: "LU", flag: "LUX", text: "Luxembourg" },
  { value: "MO", flag: "MAC", text: "Macao" },
  { value: "MG", flag: "MDG", text: "Madagascar" },
  { value: "MW", flag: "MWI", text: "Malawi" },
  { value: "MY", flag: "MYS", text: "Malaysia" },
  { value: "MV", flag: "MDV", text: "Maldives" },
  { value: "ML", flag: "MLI", text: "Mali" },
  { value: "MT", flag: "MLT", text: "Malta" },
  { value: "MH", flag: "MHL", text: "Marshall Islands (the)" },
  { value: "MQ", flag: "MTQ", text: "Martinique" },
  { value: "MR", flag: "MRT", text: "Mauritania" },
  { value: "MU", flag: "MUS", text: "Mauritius" },
  { value: "YT", flag: "MYT", text: "Mayotte" },
  { value: "MX", flag: "MEX", text: "Mexico" },
  { value: "FM", flag: "FSM", text: "Micronesia (Federated States of)" },
  { value: "MD", flag: "MDA", text: "Moldova (the Republic of)" },
  { value: "MC", flag: "MCO", text: "Monaco" },
  { value: "MN", flag: "MNG", text: "Mongolia" },
  { value: "ME", flag: "MNE", text: "Montenegro" },
  { value: "MS", flag: "MSR", text: "Montserrat" },
  { value: "MA", flag: "MAR", text: "Morocco" },
  { value: "MZ", flag: "MOZ", text: "Mozambique" },
  { value: "MM", flag: "MMR", text: "Myanmar" },
  { value: "NA", flag: "NAM", text: "Namibia" },
  { value: "NR", flag: "NRU", text: "Nauru" },
  { value: "NP", flag: "NPL", text: "Nepal" },
  { value: "NL", flag: "NLD", text: "Netherlands (the)" },
  { value: "NC", flag: "NCL", text: "New Caledonia" },
  { value: "NZ", flag: "NZL", text: "New Zealand" },
  { value: "NI", flag: "NIC", text: "Nicaragua" },
  { value: "NE", flag: "NER", text: "Niger (the)" },
  { value: "NG", flag: "NGA", text: "Nigeria" },
  { value: "NU", flag: "NIU", text: "Niue" },
  { value: "NF", flag: "NFK", text: "Norfolk Island" },
  { value: "MP", flag: "MNP", text: "Northern Mariana Islands (the)" },
  { value: "NO", flag: "NOR", text: "Norway" },
  { value: "OM", flag: "OMN", text: "Oman" },
  { value: "PK", flag: "PAK", text: "Pakistan" },
  { value: "PW", flag: "PLW", text: "Palau" },
  { value: "PS", flag: "PSE", text: "Palestine, State of" },
  { value: "PA", flag: "PAN", text: "Panama" },
  { value: "PG", flag: "PNG", text: "Papua New Guinea" },
  { value: "PY", flag: "PRY", text: "Paraguay" },
  { value: "PE", flag: "PER", text: "Peru" },
  { value: "PH", flag: "PHL", text: "Philippines (the)" },
  { value: "PN", flag: "PCN", text: "Pitcairn" },
  { value: "PL", flag: "POL", text: "Poland" },
  { value: "PT", flag: "PRT", text: "Portugal" },
  { value: "PR", flag: "PRI", text: "Puerto Rico" },
  { value: "QA", flag: "QAT", text: "Qatar" },
  { value: "MK", flag: "MKD", text: "Republic of North Macedonia" },
  { value: "RO", flag: "ROU", text: "Romania" },
  { value: "RU", flag: "RUS", text: "Russian Federation (the)" },
  { value: "RW", flag: "RWA", text: "Rwanda" },
  { value: "RE", flag: "REU", text: "Réunion" },
  { value: "BL", flag: "BLM", text: "Saint Barthélemy" },
  {
    value: "SH",
    flag: "SHN",
    text: "Saint Helena, Ascension and Tristan da Cunha",
  },
  { value: "KN", flag: "KNA", text: "Saint Kitts and Nevis" },
  { value: "LC", flag: "LCA", text: "Saint Lucia" },
  { value: "MF", flag: "MAF", text: "Saint Martin (French part)" },
  { value: "PM", flag: "SPM", text: "Saint Pierre and Miquelon" },
  { value: "VC", flag: "VCT", text: "Saint Vincent and the Grenadines" },
  { value: "WS", flag: "WSM", text: "Samoa" },
  { value: "SM", flag: "SMR", text: "San Marino" },
  { value: "ST", flag: "STP", text: "Sao Tome and Principe" },
  { value: "SA", flag: "SAU", text: "Saudi Arabia" },
  { value: "SN", flag: "SEN", text: "Senegal" },
  { value: "RS", flag: "SRB", text: "Serbia" },
  { value: "SC", flag: "SYC", text: "Seychelles" },
  { value: "SL", flag: "SLE", text: "Sierra Leone" },
  { value: "sg", flag: "SGP", text: "Singapore" },
  { value: "sx", flag: "SXM", text: "Sint Maarten (Dutch part)" },
  { value: "sk", flag: "SVK", text: "Slovakia" },
  { value: "SI", flag: "SVN", text: "Slovenia" },
  { value: "SB", flag: "SLB", text: "Solomon Islands" },
  { value: "SO", flag: "SOM", text: "Somalia" },
  { value: "ZA", flag: "ZAF", text: "South Africa" },
  {
    value: "GS",
    flag: "SGS",
    text: "South Georgia and the South Sandwich Islands",
  },
  { value: "SS", flag: "SSD", text: "South Sudan" },
  { value: "ES", flag: "ESP", text: "Spain" },
  { value: "LK", flag: "LKA", text: "Sri Lanka" },
  { value: "SD", flag: "SDN", text: "Sudan (the)" },
  { value: "SR", flag: "SUR", text: "Suritext" },
  { value: "SJ", flag: "SJM", text: "Svalbard and Jan Mayen" },
  { value: "SE", flag: "SWE", text: "Sweden" },
  { value: "CH", flag: "CHE", text: "Switzerland" },
  { value: "SY", flag: "SYR", text: "Syrian Arab Republic" },
  { value: "TW", flag: "TWN", text: "Taiwan" },
  { value: "TJ", flag: "TJK", text: "Tajikistan" },
  { value: "TZ", flag: "TZA", text: "Tanzania, United Republic of" },
  { value: "TH", flag: "THA", text: "Thailand" },
  { value: "TL", flag: "TLS", text: "Timor-Leste" },
  { value: "TG", flag: "TGO", text: "Togo" },
  { value: "TK", flag: "TKL", text: "Tokelau" },
  { value: "TO", flag: "TON", text: "Tonga" },
  { value: "TT", flag: "TTO", text: "Trinidad and Tobago" },
  { value: "TN", flag: "TUN", text: "Tunisia" },
  { value: "TR", flag: "TUR", text: "Turkey" },
  { value: "TM", flag: "TKM", text: "Turkmenistan" },
  { value: "TC", flag: "TCA", text: "Turks and Caicos Islands (the)" },
  { value: "TV", flag: "TUV", text: "Tuvalu" },
  { value: "UG", flag: "UGA", text: "Uganda" },
  { value: "UA", flag: "UKR", text: "Ukraine" },
  { value: "AE", flag: "ARE", text: "United Arab Emirates (the)" },
  {
    value: "GB",
    flag: "GBR",
    text: "United Kingdom of Great Britain and Northern Ireland (the)",
  },
  {
    value: "UM",
    flag: "UMI",
    text: "United States Minor Outlying Islands (the)",
  },
  { value: "US", flag: "USA", text: "United States of America (the)" },
  { value: "UY", flag: "URY", text: "Uruguay" },
  { value: "UZ", flag: "UZB", text: "Uzbekistan" },
  { value: "VU", flag: "VUT", text: "Vanuatu" },
  { value: "VE", flag: "VEN", text: "Venezuela (Bolivarian Republic of)" },
  { value: "VN", flag: "VNM", text: "Viet Nam" },
  { value: "VG", flag: "VGB", text: "Virgin Islands (British)" },
  { value: "VI", flag: "VIR", text: "Virgin Islands (U.S.)" },
  { value: "WF", flag: "WLF", text: "Wallis and Futuna" },
  { value: "EH", flag: "ESH", text: "Western Sahara" },
  { value: "YE", flag: "YEM", text: "Yemen" },
  { value: "ZM", flag: "ZMB", text: "Zambia" },
  { value: "ZW", flag: "ZWE", text: "Zimbabwe" },
];

export default CountryData;

export const CountryOptions = [
  { key: "af", value: "af", flag: "af", text: "Afghanistan" },
  { key: "ax", value: "ax", flag: "ax", text: "Aland Islands" },
  { key: "al", value: "al", flag: "al", text: "Albania" },
  { key: "dz", value: "dz", flag: "dz", text: "Algeria" },
  { key: "as", value: "as", flag: "as", text: "American Samoa" },
  { key: "ad", value: "ad", flag: "ad", text: "Andorra" },
  { key: "ao", value: "ao", flag: "ao", text: "Angola" },
  { key: "ai", value: "ai", flag: "ai", text: "Anguilla" },
  { key: "ag", value: "ag", flag: "ag", text: "Antigua" },
  { key: "ar", value: "ar", flag: "ar", text: "Argentina" },
  { key: "am", value: "am", flag: "am", text: "Armenia" },
  { key: "aw", value: "aw", flag: "aw", text: "Aruba" },
  { key: "au", value: "au", flag: "au", text: "Australia" },
  { key: "at", value: "at", flag: "at", text: "Austria" },
  { key: "az", value: "az", flag: "az", text: "Azerbaijan" },
  { key: "bs", value: "bs", flag: "bs", text: "Bahamas" },
  { key: "bh", value: "bh", flag: "bh", text: "Bahrain" },
  { key: "bd", value: "bd", flag: "bd", text: "Bangladesh" },
  { key: "bb", value: "bb", flag: "bb", text: "Barbados" },
  { key: "by", value: "by", flag: "by", text: "Belarus" },
  { key: "be", value: "be", flag: "be", text: "Belgium" },
  { key: "bz", value: "bz", flag: "bz", text: "Belize" },
  { key: "bj", value: "bj", flag: "bj", text: "Benin" },
];
